<?php
/**
 * Settings class for the plugin.
 */

if (!defined('ABSPATH')) {
    exit;
}

class Glint_AI_WC_Settings
{

    public function __construct()
    {
        add_action('admin_menu', array($this, 'add_admin_menu'));
        add_action('admin_init', array($this, 'register_settings'));
    }

    /**
     * Add menu pages
     */
    public function add_admin_menu()
    {
        add_menu_page(
            __('ST Chat Agent', 'glint-ai-wc'),
            __('ST Chat Agent', 'glint-ai-wc'),
            'manage_options',
            'glint-ai-agent-settings',
            array($this, 'render_settings_page'),
            'dashicons-robot',
            56
        );

        add_submenu_page(
            'glint-ai-agent-settings',
            __('Settings', 'glint-ai-wc'),
            __('Settings', 'glint-ai-wc'),
            'manage_options',
            'glint-ai-agent-settings',
            array($this, 'render_settings_page')
        );

        add_submenu_page(
            'glint-ai-agent-settings',
            __('API Endpoints', 'glint-ai-wc'),
            __('API Endpoints', 'glint-ai-wc'),
            'manage_options',
            'glint-ai-agent-endpoints',
            array($this, 'render_endpoints_page')
        );
    }

    /**
     * Register plugin settings
     */
    public function register_settings()
    {
        // Coupon Settings Section
        add_settings_section(
            'glint_ai_wc_coupon_section',
            __('Coupon Generation Settings', 'glint-ai-wc'),
            array($this, 'coupon_section_cb'),
            'glint-ai-agent-settings'
        );

        register_setting('glint_ai_wc_settings_group', 'glint_ai_wc_coupon_discount_type');
        register_setting('glint_ai_wc_settings_group', 'glint_ai_wc_coupon_amount');
        register_setting('glint_ai_wc_settings_group', 'glint_ai_wc_coupon_expiry_days');
        register_setting('glint_ai_wc_settings_group', 'glint_ai_wc_coupon_categories');

        add_settings_field(
            'glint_ai_wc_coupon_discount_type',
            __('Discount Type', 'glint-ai-wc'),
            array($this, 'coupon_discount_type_cb'),
            'glint-ai-agent-settings',
            'glint_ai_wc_coupon_section'
        );

        add_settings_field(
            'glint_ai_wc_coupon_amount',
            __('Discount Amount', 'glint-ai-wc'),
            array($this, 'coupon_amount_cb'),
            'glint-ai-agent-settings',
            'glint_ai_wc_coupon_section'
        );

        add_settings_field(
            'glint_ai_wc_coupon_expiry_days',
            __('Expiry (Days)', 'glint-ai-wc'),
            array($this, 'coupon_expiry_days_cb'),
            'glint-ai-agent-settings',
            'glint_ai_wc_coupon_section'
        );

        add_settings_field(
            'glint_ai_wc_coupon_categories',
            __('Applicable Categories (IDs)', 'glint-ai-wc'),
            array($this, 'coupon_categories_cb'),
            'glint-ai-agent-settings',
            'glint_ai_wc_coupon_section'
        );
    }

    public function coupon_section_cb()
    {
        echo '<p>' . esc_html__('Configure the rules for coupons generated by the AI Agent.', 'glint-ai-wc') . '</p>';
    }

    public function coupon_discount_type_cb()
    {
        $type = get_option('glint_ai_wc_coupon_discount_type', 'percent');
        ?>
        <select name="glint_ai_wc_coupon_discount_type">
            <option value="percent" <?php selected($type, 'percent'); ?>>
                <?php esc_html_e('Percentage discount', 'glint-ai-wc'); ?></option>
            <option value="fixed_cart" <?php selected($type, 'fixed_cart'); ?>>
                <?php esc_html_e('Fixed cart discount', 'glint-ai-wc'); ?></option>
            <option value="fixed_product" <?php selected($type, 'fixed_product'); ?>>
                <?php esc_html_e('Fixed product discount', 'glint-ai-wc'); ?></option>
        </select>
        <?php
    }

    public function coupon_amount_cb()
    {
        $amount = get_option('glint_ai_wc_coupon_amount', '10');
        echo '<input type="number" step="0.01" name="glint_ai_wc_coupon_amount" value="' . esc_attr($amount) . '" class="regular-text" />';
    }

    public function coupon_expiry_days_cb()
    {
        $days = get_option('glint_ai_wc_coupon_expiry_days', '7');
        echo '<input type="number" step="1" name="glint_ai_wc_coupon_expiry_days" value="' . esc_attr($days) . '" class="regular-text" />';
        echo '<p class="description">' . esc_html__('Number of days the coupon is valid from the time it is generated.', 'glint-ai-wc') . '</p>';
    }

    public function coupon_categories_cb()
    {
        $categories = get_option('glint_ai_wc_coupon_categories', '');
        echo '<input type="text" name="glint_ai_wc_coupon_categories" value="' . esc_attr($categories) . '" class="regular-text" />';
        echo '<p class="description">' . esc_html__('Comma-separated list of product category IDs. Leave blank to apply to all products.', 'glint-ai-wc') . '</p>';
    }

    /**
     * Render main settings page
     */
    public function render_settings_page()
    {
        require_once GLINT_AI_WC_PLUGIN_DIR . 'views/settings-page.php';
    }

    /**
     * Render endpoints page
     */
    public function render_endpoints_page()
    {
        require_once GLINT_AI_WC_PLUGIN_DIR . 'views/endpoints-page.php';
    }
}
